import './globals.css'
import type {Metadata} from 'next'
import {Roboto} from "next/font/google";
import React from "react";
import Header from "@/app/components/header/Header";
import './globals.css';

const inter = Roboto({subsets: ['latin'], weight: '400'})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header></Header>
        {children}
        </body>
        </html>
    )
}
